// Code generated by dagger-compiler.  Do not edit.
package com.zynga.zcafe.fragments;


import dagger.MembersInjector;
import dagger.internal.Binding;
import dagger.internal.Linker;
import java.util.Set;
import javax.inject.Provider;

/**
 * A {@code Binder<RegistrationFragment>} implementation which satisfies
 * Dagger's infrastructure requirements including:
 *
 * Owning the dependency links between {@code RegistrationFragment} and its
 * dependencies.
 *
 * Being a {@code Provider<RegistrationFragment>} and handling creation and
 * preparation of object instances.
 *
 * Being a {@code MembersInjector<RegistrationFragment>} and handling injection
 * of annotated fields.
 */
public final class RegistrationFragment$$InjectAdapter extends Binding<RegistrationFragment>
    implements Provider<RegistrationFragment>, MembersInjector<RegistrationFragment> {
  private Binding<com.zynga.zcafe.inject.modules.CafeModule.MainThreadBus> mainBus;
  private Binding<com.zynga.zcafe.services.CafeService> service;

  public RegistrationFragment$$InjectAdapter() {
    super("com.zynga.zcafe.fragments.RegistrationFragment", "members/com.zynga.zcafe.fragments.RegistrationFragment", NOT_SINGLETON, RegistrationFragment.class);
  }

  /**
   * Used internally to link bindings/providers together at run time
   * according to their dependency graph.
   */
  @Override
  @SuppressWarnings("unchecked")
  public void attach(Linker linker) {
    mainBus = (Binding<com.zynga.zcafe.inject.modules.CafeModule.MainThreadBus>) linker.requestBinding("com.zynga.zcafe.inject.modules.CafeModule$MainThreadBus", RegistrationFragment.class, getClass().getClassLoader());
    service = (Binding<com.zynga.zcafe.services.CafeService>) linker.requestBinding("com.zynga.zcafe.services.CafeService", RegistrationFragment.class, getClass().getClassLoader());
  }

  /**
   * Used internally obtain dependency information, such as for cyclical
   * graph detection.
   */
  @Override
  public void getDependencies(Set<Binding<?>> getBindings, Set<Binding<?>> injectMembersBindings) {
    injectMembersBindings.add(mainBus);
    injectMembersBindings.add(service);
  }

  /**
   * Returns the fully provisioned instance satisfying the contract for
   * {@code Provider<RegistrationFragment>}.
   */
  @Override
  public RegistrationFragment get() {
    RegistrationFragment result = new RegistrationFragment();
    injectMembers(result);
    return result;
  }

  /**
   * Injects any {@code @Inject} annotated fields in the given instance,
   * satisfying the contract for {@code Provider<RegistrationFragment>}.
   */
  @Override
  public void injectMembers(RegistrationFragment object) {
    object.mainBus = mainBus.get();
    object.service = service.get();
  }
}
