// Code generated by dagger-compiler.  Do not edit.
package com.zynga.zcafe.activities;


import dagger.MembersInjector;
import dagger.internal.Binding;
import dagger.internal.Linker;
import java.util.Set;
import javax.inject.Provider;

/**
 * A {@code Binder<CafeActivity>} implementation which satisfies
 * Dagger's infrastructure requirements including:
 *
 * Owning the dependency links between {@code CafeActivity} and its
 * dependencies.
 *
 * Being a {@code Provider<CafeActivity>} and handling creation and
 * preparation of object instances.
 *
 * Being a {@code MembersInjector<CafeActivity>} and handling injection
 * of annotated fields.
 */
public final class CafeActivity$$InjectAdapter extends Binding<CafeActivity>
    implements Provider<CafeActivity>, MembersInjector<CafeActivity> {
  private Binding<com.zynga.zcafe.CafeApplication> app;
  private Binding<com.zynga.zcafe.inject.modules.CafeModule.MainThreadBus> bus;
  private Binding<com.zynga.zcafe.services.CafeService> service;

  public CafeActivity$$InjectAdapter() {
    super("com.zynga.zcafe.activities.CafeActivity", "members/com.zynga.zcafe.activities.CafeActivity", NOT_SINGLETON, CafeActivity.class);
  }

  /**
   * Used internally to link bindings/providers together at run time
   * according to their dependency graph.
   */
  @Override
  @SuppressWarnings("unchecked")
  public void attach(Linker linker) {
    app = (Binding<com.zynga.zcafe.CafeApplication>) linker.requestBinding("com.zynga.zcafe.CafeApplication", CafeActivity.class, getClass().getClassLoader());
    bus = (Binding<com.zynga.zcafe.inject.modules.CafeModule.MainThreadBus>) linker.requestBinding("com.zynga.zcafe.inject.modules.CafeModule$MainThreadBus", CafeActivity.class, getClass().getClassLoader());
    service = (Binding<com.zynga.zcafe.services.CafeService>) linker.requestBinding("com.zynga.zcafe.services.CafeService", CafeActivity.class, getClass().getClassLoader());
  }

  /**
   * Used internally obtain dependency information, such as for cyclical
   * graph detection.
   */
  @Override
  public void getDependencies(Set<Binding<?>> getBindings, Set<Binding<?>> injectMembersBindings) {
    injectMembersBindings.add(app);
    injectMembersBindings.add(bus);
    injectMembersBindings.add(service);
  }

  /**
   * Returns the fully provisioned instance satisfying the contract for
   * {@code Provider<CafeActivity>}.
   */
  @Override
  public CafeActivity get() {
    CafeActivity result = new CafeActivity();
    injectMembers(result);
    return result;
  }

  /**
   * Injects any {@code @Inject} annotated fields in the given instance,
   * satisfying the contract for {@code Provider<CafeActivity>}.
   */
  @Override
  public void injectMembers(CafeActivity object) {
    object.app = app.get();
    object.bus = bus.get();
    object.service = service.get();
  }
}
