// Code generated by dagger-compiler.  Do not edit.
package com.zynga.zcafe.activities;


import dagger.MembersInjector;
import dagger.internal.Binding;
import dagger.internal.Linker;
import java.util.Set;
import javax.inject.Provider;

/**
 * A {@code Binder<RegistrationActivity>} implementation which satisfies
 * Dagger's infrastructure requirements including:
 *
 * Owning the dependency links between {@code RegistrationActivity} and its
 * dependencies.
 *
 * Being a {@code Provider<RegistrationActivity>} and handling creation and
 * preparation of object instances.
 *
 * Being a {@code MembersInjector<RegistrationActivity>} and handling injection
 * of annotated fields.
 */
public final class RegistrationActivity$$InjectAdapter extends Binding<RegistrationActivity>
    implements Provider<RegistrationActivity>, MembersInjector<RegistrationActivity> {
  private Binding<com.zynga.zcafe.inject.modules.CafeModule.MainThreadBus> bus;

  public RegistrationActivity$$InjectAdapter() {
    super("com.zynga.zcafe.activities.RegistrationActivity", "members/com.zynga.zcafe.activities.RegistrationActivity", NOT_SINGLETON, RegistrationActivity.class);
  }

  /**
   * Used internally to link bindings/providers together at run time
   * according to their dependency graph.
   */
  @Override
  @SuppressWarnings("unchecked")
  public void attach(Linker linker) {
    bus = (Binding<com.zynga.zcafe.inject.modules.CafeModule.MainThreadBus>) linker.requestBinding("com.zynga.zcafe.inject.modules.CafeModule$MainThreadBus", RegistrationActivity.class, getClass().getClassLoader());
  }

  /**
   * Used internally obtain dependency information, such as for cyclical
   * graph detection.
   */
  @Override
  public void getDependencies(Set<Binding<?>> getBindings, Set<Binding<?>> injectMembersBindings) {
    injectMembersBindings.add(bus);
  }

  /**
   * Returns the fully provisioned instance satisfying the contract for
   * {@code Provider<RegistrationActivity>}.
   */
  @Override
  public RegistrationActivity get() {
    RegistrationActivity result = new RegistrationActivity();
    injectMembers(result);
    return result;
  }

  /**
   * Injects any {@code @Inject} annotated fields in the given instance,
   * satisfying the contract for {@code Provider<RegistrationActivity>}.
   */
  @Override
  public void injectMembers(RegistrationActivity object) {
    object.bus = bus.get();
  }
}
