// Code generated by dagger-compiler.  Do not edit.
package com.zynga.zcafe;


import dagger.MembersInjector;
import dagger.internal.Binding;
import dagger.internal.Linker;
import java.util.Set;
import javax.inject.Provider;

/**
 * A {@code Binder<CafeApplication>} implementation which satisfies
 * Dagger's infrastructure requirements including:
 *
 * Owning the dependency links between {@code CafeApplication} and its
 * dependencies.
 *
 * Being a {@code Provider<CafeApplication>} and handling creation and
 * preparation of object instances.
 *
 * Being a {@code MembersInjector<CafeApplication>} and handling injection
 * of annotated fields.
 */
public final class CafeApplication$$InjectAdapter extends Binding<CafeApplication>
    implements Provider<CafeApplication>, MembersInjector<CafeApplication> {
  private Binding<com.zynga.zcafe.events.Producers> producers;

  public CafeApplication$$InjectAdapter() {
    super("com.zynga.zcafe.CafeApplication", "members/com.zynga.zcafe.CafeApplication", NOT_SINGLETON, CafeApplication.class);
  }

  /**
   * Used internally to link bindings/providers together at run time
   * according to their dependency graph.
   */
  @Override
  @SuppressWarnings("unchecked")
  public void attach(Linker linker) {
    producers = (Binding<com.zynga.zcafe.events.Producers>) linker.requestBinding("com.zynga.zcafe.events.Producers", CafeApplication.class, getClass().getClassLoader());
  }

  /**
   * Used internally obtain dependency information, such as for cyclical
   * graph detection.
   */
  @Override
  public void getDependencies(Set<Binding<?>> getBindings, Set<Binding<?>> injectMembersBindings) {
    injectMembersBindings.add(producers);
  }

  /**
   * Returns the fully provisioned instance satisfying the contract for
   * {@code Provider<CafeApplication>}.
   */
  @Override
  public CafeApplication get() {
    CafeApplication result = new CafeApplication();
    injectMembers(result);
    return result;
  }

  /**
   * Injects any {@code @Inject} annotated fields in the given instance,
   * satisfying the contract for {@code Provider<CafeApplication>}.
   */
  @Override
  public void injectMembers(CafeApplication object) {
    object.producers = producers.get();
  }
}
